services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app:delegated
            - /app/node_modules
        environment:
            - WATCHPACK_POLLING=true
            - CHOKIDAR_USEPOLLING=true
            - WDS_SOCKET_PORT=0
            - REACT_APP_API_URL=http://127.0.0.1:8000/api/
        stdin_open: true
        tty: true
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./backend:/var/www/html
